### ISSUE TITLE
Owner book detail needs to show current borrower

### ISSUE THREAD

**Issue by xichen1** [CMPUT301F20T35/BookIt#84]
As the description shows:
![image](https://user-images.githubusercontent.com/47851834/100164213-a8529300-2e74-11eb-83c4-65d23bf3b759.png)

Solutions:
1) add the borrow field to all book details and show no name in other books
2) create special book detail page for owner borrowed book

**Comment by shawnxxxu** [comment]
1

**Comment by xichen1** [comment]
fixed
